#!/usr/bin/env node
// Node.js 22+, no dependencies. Human reviewers remain responsible for factual accuracy.
import { readFile, readdir, mkdir, rename, writeFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const TIMEZONE = 'America/Los_Angeles';
const DEFAULT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OWNED_MARKER = '<!-- Generated by scripts/report.mjs. Edit source JSON, not this file. -->';
const PLACEHOLDER = /\b(?:TODO|TBD|PLACEHOLDER|REPLACE_ME|YOUR_[A-Z_]+)\b|example\.(?:com|org|net)/i;
const CJK = /[\u3040-\u30ff\u3400-\u9fff\uac00-\ud7af]/u;
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const TIMESTAMP = /^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d{1,3})?(?:Z|[+-](?:0\d|1[0-4]):[0-5]\d)$/;
const nonempty = value => typeof value === 'string' && value.trim().length > 0;
const isObject = value => value !== null && typeof value === 'object' && !Array.isArray(value);
export function isDate(value) {
  return typeof value === 'string' && DATE.test(value) && !Number.isNaN(Date.parse(value)) && new Date(value).toISOString().slice(0, 10) === value;
}
function isTimestamp(value) {
  return typeof value === 'string' && TIMESTAMP.test(value) && isDate(value.slice(0, 10)) && !Number.isNaN(Date.parse(value));
}
function isHttps(value) {
  try { const url = new URL(value); return typeof value === 'string' && !/\s/.test(value) && url.protocol === 'https:' && !url.username && !url.password && !PLACEHOLDER.test(value); } catch { return false; }
}
function dateParts(value, timezone = TIMEZONE) {
  return Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).formatToParts(value).filter(part => part.type !== 'literal').map(part => [part.type, part.value]));
}
export function localDate(value = new Date(), timezone = TIMEZONE) {
  const p = dateParts(value, timezone);
  return `${p.year}-${p.month}-${p.day}`;
}
function calendarOffset(date, days) {
  const value = new Date(`${date}T12:00:00Z`);
  value.setUTCDate(value.getUTCDate() + days);
  return value.toISOString().slice(0, 10);
}
export function localTimestamp(date, time = '03:00', timezone = TIMEZONE) {
  if (!isDate(date) || !/^([01]\d|2[0-3]):[0-5]\d$/.test(time)) throw new Error('Invalid local date or time.');
  const target = `${date}T${time}:00`;
  const nominal = Date.parse(`${target}Z`);
  const matches = [];
  // Check timezone offsets, including half/quarter-hour zones; reject ambiguous local times.
  for (let minutes = -14 * 60; minutes <= 14 * 60; minutes += 15) {
    const instant = new Date(nominal - minutes * 60_000);
    const p = dateParts(instant, timezone);
    if (`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}` === target) matches.push(minutes);
  }
  if (matches.length !== 1) throw new Error(`Local time ${target} is nonexistent or ambiguous in ${timezone}.`);
  const minutes = matches[0];
  const abs = Math.abs(minutes);
  return `${target}${minutes >= 0 ? '+' : '-'}${String(Math.floor(abs / 60)).padStart(2, '0')}:${String(abs % 60).padStart(2, '0')}`;
}
export function scheduledWindow(date, config = {}) {
  const timezone = config.timezone ?? TIMEZONE;
  const time = config.schedule?.local_time ?? '03:00';
  return { start: localTimestamp(calendarOffset(date, -1), time, timezone), end: localTimestamp(date, time, timezone) };
}

export function canonicalKey(value) {
  try {
    const url = new URL(value);
    const host = url.hostname.toLowerCase().replace(/^www\./, '');
    if (host === 'arxiv.org' || host === 'export.arxiv.org') {
      const identifier = url.pathname.replace(/^\/(?:abs|pdf|html)\//, '').replace(/\.pdf$/i, '').replace(/v\d+$/i, '');
      return `arxiv:${identifier.toLowerCase()}`;
    }
    if (host === 'doi.org' || host === 'dx.doi.org') return `doi:${decodeURIComponent(url.pathname.slice(1)).toLowerCase()}`;
    url.hostname = host;
    url.hash = '';
    for (const key of [...url.searchParams.keys()]) if (/^utm_|^(?:ref|source|fbclid|gclid)$/i.test(key)) url.searchParams.delete(key);
    url.searchParams.sort();
    return url.toString().replace(/\/$/, '');
  } catch { return String(value); }
}
function identityKeys(entry) {
  return [...new Set([entry.canonical_url, entry.links?.paper].filter(Boolean).map(canonicalKey))];
}
function stableId(value) {
  return typeof value === 'string' && value.startsWith('arxiv:') ? value.replace(/v\d+$/, '') : value;
}
export function validateReport(report, { taxonomy, config = {}, filePath, now = new Date() } = {}) {
  const errors = [];
  const fail = message => errors.push(message);
  if (!isObject(report)) return ['Report must be an object.'];
  const object = (value, label, allowed) => {
    if (!isObject(value)) { fail(`${label} must be an object.`); return false; }
    for (const key of Object.keys(value)) if (!allowed.includes(key)) fail(`${label}: unknown property ${key}.`);
    return true;
  };
  const prose = (value, label, allowEmpty = false) => {
    if (typeof value !== 'string' || (!allowEmpty && !nonempty(value))) fail(`${label} must be a nonempty string.`);
    else if (PLACEHOLDER.test(value)) fail(`${label} contains a placeholder.`);
  };
  const landscape = report.kind === 'landscape';
  object(report, 'Report', ['schema_version', 'kind', 'date', 'timezone', 'generated_at', 'coverage', 'search', 'entries', 'overview']);
  if (report.kind !== undefined && !['daily', 'landscape'].includes(report.kind)) fail('kind must be daily or landscape.');
  if (report.overview !== undefined) {
    if (!landscape || !isObject(report.overview)) fail('overview is only supported for landscape snapshots.');
    else for (const [group, value] of Object.entries(report.overview)) {
      if (!taxonomy?.groups?.some(item => item.id === group)) fail(`overview: unknown group ${group}.`);
      prose(value, `overview.${group}`);
    }
  }
  if (report.schema_version !== 1) fail('schema_version must be 1.');
  if (!isDate(report.date)) fail('date must be a valid YYYY-MM-DD date.');
  if (report.timezone !== TIMEZONE || report.timezone !== (config.timezone ?? TIMEZONE)) fail(`timezone must be ${TIMEZONE}.`);
  if (isDate(report.date) && report.date > localDate(now)) fail('date cannot be in the future.');
  if (!landscape && isDate(config.delta_start_date) && isDate(report.date) && report.date < config.delta_start_date) fail(`Daily deltas begin on ${config.delta_start_date}; pre-baseline backfill is not allowed.`);
  if (!isTimestamp(report.generated_at)) fail('generated_at must be an ISO timestamp with an explicit offset.');
  else if (Date.parse(report.generated_at) > now.getTime() + 300_000) fail('generated_at cannot be in the future (five-minute clock tolerance).');
  if (filePath && isDate(report.date)) {
    const expected = landscape ? `data/landscapes/${report.date}.json` : `data/reports/${report.date.slice(0, 4)}/${report.date.slice(5, 7)}/${report.date}.json`;
    if (filePath.replaceAll('\\', '/') !== expected) fail(`Report path must be ${expected}.`);
  }
  if (landscape && report.coverage !== undefined) fail('Landscape snapshots use an as-of date, not a daily coverage window.');
  if (!landscape && object(report.coverage, 'coverage', ['start', 'end'])) {
    for (const key of ['start', 'end']) if (!isTimestamp(report.coverage[key])) fail(`coverage.${key} must be an ISO timestamp with an explicit offset.`);
    if (isTimestamp(report.coverage.start) && isTimestamp(report.coverage.end)) {
      if (Date.parse(report.coverage.start) >= Date.parse(report.coverage.end)) fail('coverage.start must precede coverage.end.');
      if (isTimestamp(report.generated_at) && Date.parse(report.coverage.end) > Date.parse(report.generated_at)) fail('coverage.end must not be after generated_at.');
      if (isDate(report.date)) {
        const expected = scheduledWindow(report.date, config);
        if (Date.parse(expected.start) !== Date.parse(report.coverage.start) || Date.parse(expected.end) !== Date.parse(report.coverage.end)) fail('coverage must span consecutive scheduled local 03:00 cutoffs.');
      }
    }
  }
  if (object(report.search, 'search', ['status', 'notes', 'sources_checked'])) {
    if (!['complete', 'partial'].includes(report.search.status)) fail('search.status must be complete or partial.');
    prose(report.search.notes, 'search.notes', report.search.status === 'complete');
    if (!Array.isArray(report.search.sources_checked) || report.search.sources_checked.length === 0) fail('search.sources_checked must list at least one checked source.');
    else report.search.sources_checked.forEach((source, i) => {
      if (!object(source, `search.sources_checked[${i}]`, ['name', 'url', 'status'])) return;
      prose(source.name, `search.sources_checked[${i}].name`);
      if (!isHttps(source.url)) fail(`search.sources_checked[${i}].url must be a real HTTPS URL.`);
      if (!['ok', 'unavailable'].includes(source.status)) fail(`search.sources_checked[${i}].status must be ok or unavailable.`);
      if (source.status === 'unavailable' && report.search.status === 'complete') fail('An unavailable source requires search.status partial.');
    });
    if (Array.isArray(report.search.sources_checked) && !report.search.sources_checked.some(source => source?.status === 'ok')) fail('At least one source must be checked successfully; total retrieval failure is not publishable.');
  }
  const categories = new Set(taxonomy?.groups?.flatMap(group => group.topics.map(topic => topic.id)) ?? []);
  if (categories.size === 0) fail('A nonempty taxonomy is required.');
  if (!Array.isArray(report.entries)) { fail('entries must be an array.'); return errors; }
  if (!landscape && report.entries.length > (config.max_entries ?? 10)) fail(`entries exceeds max_entries (${config.max_entries ?? 10}).`);
  if (landscape && report.entries.length === 0) fail('A landscape snapshot must include reviewed research.');
  const ids = new Set();
  const identities = new Set();
  report.entries.forEach((entry, i) => {
    const label = `entries[${i}]`;
    if (!object(entry, label, ['id', 'title', 'category', 'tags', 'published_on', 'first_seen_at', 'canonical_url', 'links', 'summary', 'evidence', 'novelty', 'update_note', 'positioning', 'public_availability'])) return;
    if (!nonempty(entry.id) || !/^[a-z0-9][a-z0-9._:/-]*$/.test(entry.id)) fail(`${label}.id must be a lowercase stable identifier.`);
    if (ids.has(stableId(entry.id))) fail(`${label}: duplicate id ${entry.id}.`);
    ids.add(stableId(entry.id));
    prose(entry.title, `${label}.title`);
    if (!categories.has(entry.category)) fail(`${label}.category is not in the taxonomy.`);
    if (!Array.isArray(entry.tags) || entry.tags.length < 2 || entry.tags.length > 4 || entry.tags.some(tag => !nonempty(tag) || PLACEHOLDER.test(tag)) || new Set(entry.tags.map(tag => typeof tag === 'string' ? tag.toLowerCase() : tag)).size !== entry.tags.length) fail(`${label}.tags must contain 2–4 distinct nonempty tags.`);
    if (!isDate(entry.published_on)) fail(`${label}.published_on must be a valid date.`);
    else if (entry.published_on > report.date || entry.published_on > localDate(now)) fail(`${label}.published_on cannot be in the future or after the report date.`);
    if (!isTimestamp(entry.first_seen_at)) fail(`${label}.first_seen_at must be an ISO timestamp with an explicit offset.`);
    else if (Date.parse(entry.first_seen_at) > now.getTime() + 300_000 || (isTimestamp(report.generated_at) && Date.parse(entry.first_seen_at) > Date.parse(report.generated_at) + 300_000)) fail(`${label}.first_seen_at cannot be after generation or in the future (five-minute clock tolerance).`);
    if (entry.public_availability !== undefined && object(entry.public_availability, `${label}.public_availability`, ['at', 'basis', 'sources'])) {
      const availability = entry.public_availability;
      if (!isTimestamp(availability.at)) fail(`${label}.public_availability.at must be an ISO timestamp with an explicit offset.`);
      else {
        const availableAt = Date.parse(availability.at);
        if (availableAt > now.getTime() || (isTimestamp(report.coverage?.end) && availableAt > Date.parse(report.coverage.end))) fail(`${label}.public_availability.at must not be after the scheduled cutoff or in the future.`);
        if (landscape && isDate(report.date) && localDate(new Date(availableAt)) > report.date) fail(`${label}.public_availability.at must not be after the landscape as-of date.`);
        if (isDate(entry.published_on) && availableAt < Date.parse(`${entry.published_on}T00:00:00Z`)) fail(`${label}.public_availability.at must not precede the retained original publication date.`);
        if (isTimestamp(entry.first_seen_at) && availableAt > Date.parse(entry.first_seen_at)) fail(`${label}.public_availability.at must not be after first_seen_at.`);
      }
      if (!['dated-source', 'announcement-schedule'].includes(availability.basis)) fail(`${label}.public_availability.basis must distinguish dated-source from announcement-schedule.`);
      if (!Array.isArray(availability.sources) || availability.sources.length === 0 || availability.sources.some(url => !isHttps(url)) || new Set(availability.sources).size !== availability.sources.length) fail(`${label}.public_availability.sources must contain distinct HTTPS sources.`);
      else if (!Array.isArray(report.search?.sources_checked) || availability.sources.some(url => !report.search.sources_checked.some(source => source?.url === url && source?.status === 'ok'))) fail(`${label}.public_availability.sources must have successful source checks in this report.`);
    }
    if (!isHttps(entry.canonical_url)) fail(`${label}.canonical_url must be a real HTTPS URL.`);
    if (object(entry.links, `${label}.links`, ['paper', 'blog', 'code', 'project'])) for (const [key, value] of Object.entries(entry.links)) if (!isHttps(value)) fail(`${label}.links.${key} must be a real HTTPS URL.`);
    const min = config.summary_sentences?.min ?? 2;
    const max = config.summary_sentences?.max ?? 3;
    if (!Array.isArray(entry.summary) || entry.summary.length < min || entry.summary.length > max) fail(`${label}.summary must contain ${min}–${max} English sentence strings.`);
    else entry.summary.forEach((sentence, j) => {
      prose(sentence, `${label}.summary[${j}]`);
      if (typeof sentence === 'string' && (CJK.test(sentence) || !/[a-z]/i.test(sentence))) fail(`${label}.summary[${j}] must be English.`);
    });
    if (object(entry.evidence, `${label}.evidence`, ['type', 'access', 'rationale', 'limitations'])) {
      if (!['research-paper', 'technical-report', 'engineering-report'].includes(entry.evidence.type)) fail(`${label}.evidence.type is invalid.`);
      if (!['full-text', 'abstract-only'].includes(entry.evidence.access)) fail(`${label}.evidence.access is invalid.`);
      prose(entry.evidence.rationale, `${label}.evidence.rationale`);
      prose(entry.evidence.limitations, `${label}.evidence.limitations`);
    }
    if (!(landscape ? ['baseline'] : ['new', 'newly-discovered', 'material-update']).includes(entry.novelty)) fail(`${label}.novelty is invalid for this report kind.`);
    if (landscape || entry.positioning !== undefined) {
      if (!['frontier-research', 'established-method', 'open-reference'].includes(entry.positioning)) fail(`${label}.positioning must distinguish frontier-research, established-method or open-reference.`);
    }
    if (entry.novelty === 'material-update' || entry.update_note !== undefined) prose(entry.update_note, `${label}.update_note`);
    if (isTimestamp(report.coverage?.end) && isDate(entry.published_on)) {
      const discoveryStartMs = Date.parse(report.coverage.end) - (config.discovery_lookback_hours ?? 72) * 3_600_000;
      const discoveryStart = localDate(new Date(discoveryStartMs));
      if (entry.public_availability !== undefined) {
        const availableAt = Date.parse(entry.public_availability?.at);
        if (entry.novelty === 'newly-discovered' && availableAt < discoveryStartMs) fail(`${label}.public_availability.at is outside the discovery lookback; a dated material update is required for older work.`);
        if (entry.novelty === 'new' && isTimestamp(report.coverage.start) && availableAt < Date.parse(report.coverage.start)) fail(`${label}.public_availability.at predates the daily coverage; use newly-discovered only within the discovery lookback.`);
      } else {
        if (entry.novelty === 'newly-discovered' && entry.published_on < discoveryStart) fail(`${label}.published_on is outside the discovery lookback; a dated material update is required for older work.`);
        if (entry.novelty === 'new' && isTimestamp(report.coverage.start) && entry.published_on < localDate(new Date(report.coverage.start))) fail(`${label}.published_on predates the daily coverage; use newly-discovered only within the discovery lookback.`);
      }
      if (entry.novelty === 'material-update' && nonempty(entry.update_note)) {
        const dates = entry.update_note.match(/\b\d{4}-\d{2}-\d{2}\b/g) ?? [];
        if (!dates.some(date => isDate(date) && date >= discoveryStart && date <= report.date)) fail(`${label}.update_note must identify a recent update date (YYYY-MM-DD) within the discovery window.`);
      }
    }
    for (const key of identityKeys(entry)) {
      if (identities.has(key)) fail(`${label}: duplicate canonical source ${key}.`);
      identities.add(key);
    }
  });
  return errors;
}

export function validateCollection(records, options) {
  const errors = [];
  const ids = new Map();
  const identities = new Map();
  const dates = new Set();
  for (const record of [...records].sort((a, b) => String(a.report?.date).localeCompare(String(b.report?.date)) || Number(b.report?.kind === 'landscape') - Number(a.report?.kind === 'landscape'))) {
    const { report, filePath } = record;
    const ownErrors = validateReport(report, { ...options, filePath });
    errors.push(...ownErrors.map(error => `${filePath}: ${error}`));
    if (!report || !Array.isArray(report.entries)) continue;
    const edition = `${report.kind === 'landscape' ? 'landscape' : 'daily'}:${report.date}`;
    if (dates.has(edition)) errors.push(`${filePath}: duplicate report date ${edition}.`);
    dates.add(edition);
    for (const entry of report.entries) {
      if (!isObject(entry)) continue;
      const updated = entry.novelty === 'material-update' && nonempty(entry.update_note) && !PLACEHOLDER.test(entry.update_note);
      const previous = [ids.get(stableId(entry.id)), ...identityKeys(entry).map(key => identities.get(key))].filter(Boolean).sort((a, b) => String(b.date).localeCompare(String(a.date)))[0];
      if (previous && report.kind !== 'landscape') {
        if (!updated) errors.push(`${filePath}: ${entry.id} repeats a source or id from ${previous.edition}; material-update and update_note are required.`);
        else {
          const updateDates = entry.update_note.match(/\b\d{4}-\d{2}-\d{2}\b/g) ?? [];
          if (!updateDates.some(date => isDate(date) && date >= previous.date && date <= report.date)) errors.push(`${filePath}: ${entry.id} update_note must identify an update on or after the previous coverage date ${previous.date} (${previous.edition}).`);
        }
      }
      const current = { edition, date: report.date };
      ids.set(stableId(entry.id), current);
      for (const key of identityKeys(entry)) identities.set(key, current);
    }
  }
  return errors;
}

const escapeText = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replace(/[\\`*_[\]#|]/g, '\\$&').replace(/\r?\n/g, ' ');
const link = (label, url) => `[${escapeText(label)}](<${url.replaceAll('>', '%3E').replaceAll('<', '%3C')}>)`;
function entryMarkdown(entry, { includeCategory = false, taxonomy } = {}) {
  const lines = [`### ${link(entry.title, entry.canonical_url)}`, '', entry.summary.map(escapeText).join(' '), ''];
  if (includeCategory) {
    const topic = taxonomy.groups.flatMap(group => group.topics).find(topic => topic.id === entry.category);
    lines.push(`**Topic:** ${escapeText(topic.title)}`, '');
  }
  lines.push(`**Published:** ${entry.published_on} · **First seen:** ${entry.first_seen_at} · **Novelty:** ${entry.novelty} · **Tags:** ${entry.tags.map(escapeText).join(', ')}`, '');
  if (entry.public_availability) lines.push(`**Public availability:** ${entry.public_availability.at} (${entry.public_availability.basis === 'announcement-schedule' ? 'inferred from dated announcement and official schedule' : 'dated primary source'}). ${entry.public_availability.sources.map(url => link('Timing source', url)).join(' · ')}`, '');
  if (entry.positioning) lines.push(`**Positioning:** ${entry.positioning}`, '');
  const links = Object.entries(entry.links).map(([key, url]) => link(key[0].toUpperCase() + key.slice(1), url));
  if (links.length) lines.push(links.join(' · '), '');
  lines.push(`**Evidence:** ${entry.evidence.type}; ${entry.evidence.access}. ${escapeText(entry.evidence.rationale)}`, '', `**Limitations:** ${escapeText(entry.evidence.limitations)}`, '');
  if (entry.evidence.access === 'abstract-only') lines.push('> **LOW CONFIDENCE — abstract only.** Full text was not reviewed; claims are limited to the available abstract.', '');
  if (entry.update_note) lines.push(`**Update:** ${escapeText(entry.update_note)}`, '');
  return lines.join('\n');
}
export function renderDaily(report, taxonomy) {
  const lines = [OWNED_MARKER, `# LLM Daily Report — ${report.date}`, '', `[All reports](../../README.md) · [Topics](../../../topics/README.md)`, '', `**Coverage:** ${report.coverage.start} → ${report.coverage.end} (${report.timezone})`, '', `**Generated:** ${report.generated_at} · **Selected:** ${report.entries.length}`, ''];
  if (report.search.status === 'partial') lines.push('> **PARTIAL SEARCH — coverage is incomplete.**', `> ${escapeText(report.search.notes)}`, '');
  else lines.push('**Search status:** complete.', '', ...(report.search.notes ? [escapeText(report.search.notes), ''] : []));
  if (!report.entries.length) lines.push(report.search.status === 'complete' ? 'No qualifying research was selected from the checked sources during this coverage window.' : 'No qualifying research was selected from the sources that could be checked; this is not a complete no-results finding.', '');
  for (const group of taxonomy.groups) {
    const topics = group.topics.filter(topic => report.entries.some(entry => entry.category === topic.id));
    if (!topics.length) continue;
    lines.push(`## ${escapeText(group.title)}`, '');
    for (const topic of topics) {
      lines.push(`### ${topic.id} ${escapeText(topic.title)}`, '');
      for (const entry of report.entries.filter(entry => entry.category === topic.id)) lines.push(entryMarkdown(entry).replace(/^### /, '#### '));
    }
  }
  lines.push('## Sources checked', '');
  for (const source of report.search.sources_checked) lines.push(`- ${link(source.name, source.url)} — ${source.status}`);
  return `${lines.join('\n').trimEnd()}\n`;
}
export function renderLandscape(report, taxonomy) {
  const lines = [OWNED_MARKER, `# LLM Research Landscape — ${report.date}`, '', '[Overview](../README.md) · [Topics](../topics/README.md) · [Daily deltas](../reports/README.md)', '', `**As of:** ${report.date} (${report.timezone}) · **Reviewed:** ${report.generated_at} · **Selected references:** ${report.entries.length}`, '', 'This is the starting research baseline, not a list of papers released today. It maps reusable methods and current research directions across the agreed taxonomy. State-of-the-art claims are scoped to the cited tasks, baselines and experimental settings; there is no single overall winner.', '', '**Positioning:** `frontier-research` means an active or emerging research direction, not an independently established best result; `established-method` is a durable method; `open-reference` is an inspectable recipe, implementation or benchmark.', '', '**Delta policy:** Subsequent daily reports compare against this baseline and the daily archive. Repeated works require a substantive, dated update.', '', `**Search status:** ${report.search.status}. ${escapeText(report.search.notes)}`, ''];
  if (report.search.status === 'partial') lines.push('> **PARTIAL SEARCH — limitations in source access are described below.**', '');
  lines.push('| Area | References |', '| --- | ---: |');
  for (const group of taxonomy.groups) lines.push(`| [${escapeText(group.title)}](#${group.id}) | ${report.entries.filter(entry => group.topics.some(topic => topic.id === entry.category)).length} |`);
  lines.push('');
  for (const group of taxonomy.groups) {
    lines.push(`<a id="${group.id}"></a>`, '', `## ${escapeText(group.title)}`, '');
    if (report.overview?.[group.id]) lines.push(`**Editorial synthesis:** ${escapeText(report.overview[group.id])}`, '');
    for (const topic of group.topics) {
      lines.push(`### ${topic.id} ${escapeText(topic.title)}`, '', escapeText(topic.description), '');
      const matches = report.entries.filter(entry => entry.category === topic.id);
      if (!matches.length) lines.push('No separately verified reference was selected for this subdomain in this snapshot.', '');
      for (const entry of matches) lines.push(entryMarkdown(entry).replace(/^### /, '#### '));
    }
  }
  lines.push('## Primary sources checked', '');
  for (const source of report.search.sources_checked) lines.push(`- ${link(source.name, source.url)} — ${source.status}`);
  return `${lines.join('\n').trimEnd()}\n`;
}
export function renderOutputs(records, taxonomy) {
  const allReports = records.map(record => record.report).sort((a, b) => b.date.localeCompare(a.date));
  const reports = allReports.filter(report => report.kind !== 'landscape');
  const landscapes = allReports.filter(report => report.kind === 'landscape');
  const outputs = new Map();
  const dailyPath = date => `reports/${date.slice(0, 4)}/${date.slice(5, 7)}/${date}.md`;
  const reportPath = report => report.kind === 'landscape' ? `landscape/${report.date}.md` : dailyPath(report.date);
  for (const report of reports) outputs.set(dailyPath(report.date), renderDaily(report, taxonomy));
  for (const report of landscapes) outputs.set(reportPath(report), renderLandscape(report, taxonomy));
  outputs.set('landscape/README.md', `${[OWNED_MARKER, '# Research landscape baselines', '', '[Overview](../README.md) · [Daily deltas](../reports/README.md)', '', ...(landscapes.length ? landscapes.map(report => `- [${report.date}](${report.date}.md) — ${report.entries.length} references`) : ['No baseline has been published yet.'])].join('\n')}\n`);
  const archive = [OWNED_MARKER, '# Daily reports', '', '[Repository overview](../README.md) · [Browse topics](../topics/README.md) · [Landscape baselines](../landscape/README.md)', ''];
  if (!reports.length) archive.push('No reports have been published yet.', '');
  else for (const report of reports) archive.push(`- [${report.date}](${dailyPath(report.date).slice('reports/'.length)}) — ${report.entries.length} selected item(s)${report.search.status === 'partial' ? ' — **PARTIAL SEARCH**' : ''}`);
  outputs.set('reports/README.md', `${archive.join('\n').trimEnd()}\n`);
  const topicIndex = [OWNED_MARKER, '# Research topics', '', '[Repository overview](../README.md) · [Daily reports](../reports/README.md)', ''];
  const topicCounts = [];
  for (const group of taxonomy.groups) {
    topicIndex.push(`## ${escapeText(group.title)}`, '');
    for (const topic of group.topics) {
      const matches = allReports.flatMap(report => report.entries.filter(entry => entry.category === topic.id).map(entry => ({ report, entry })));
      const relativePath = `${group.id}/${topic.slug}/README.md`;
      topicIndex.push(`- [${topic.id} ${escapeText(topic.title)}](${relativePath}) — ${matches.length} item(s)`);
      const lines = [OWNED_MARKER, `# ${topic.id} ${escapeText(topic.title)}`, '', escapeText(topic.description), '', '[All topics](../../README.md) · [Daily reports](../../../reports/README.md)', ''];
      if (!matches.length) lines.push('No research has been indexed under this topic yet.', '');
      for (const { report, entry } of matches) {
        lines.push(`## [${report.date}${report.kind === 'landscape' ? ' — Landscape baseline' : ''}](../../../${reportPath(report)})${report.search.status === 'partial' ? ' — PARTIAL SEARCH' : ''}`, '', entryMarkdown(entry));
      }
      outputs.set(`topics/${relativePath}`, `${lines.join('\n').trimEnd()}\n`);
      topicCounts.push({ id: topic.id, group: group.id, title: topic.title, path: `topics/${relativePath}`, count: matches.length });
    }
    topicIndex.push('');
  }
  outputs.set('topics/README.md', `${topicIndex.join('\n').trimEnd()}\n`);
  const metadata = report => ({ date: report.date, path: reportPath(report), source: report.kind === 'landscape' ? `data/landscapes/${report.date}.json` : `data/${dailyPath(report.date).replace(/\.md$/, '.json')}`, search_status: report.search.status, entries: report.entries.length });
  outputs.set('data/index.json', `${JSON.stringify({ schema_version: 1, reports: reports.map(metadata), landscapes: landscapes.map(metadata), entries: allReports.flatMap(report => report.entries.map(entry => ({ ...entry, report_kind: report.kind ?? 'daily', report_date: report.date, report_path: reportPath(report), search_status: report.search.status }))), topics: topicCounts }, null, 2)}\n`);
  return outputs;
}

async function readJson(file) { return JSON.parse(await readFile(file, 'utf8')); }
async function listFiles(directory) {
  let entries;
  try { entries = await readdir(directory, { withFileTypes: true }); } catch (error) { if (error.code === 'ENOENT') return []; throw error; }
  const result = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const absolute = path.join(directory, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`Symlinks are not allowed in managed directories: ${absolute}`);
    if (entry.isDirectory()) result.push(...await listFiles(absolute));
    else if (entry.isFile()) result.push(absolute);
  }
  return result;
}
export async function loadRepository(root) {
  const [taxonomy, config, dailyFiles, landscapeFiles] = await Promise.all([readJson(path.join(root, 'config/taxonomy.json')), readJson(path.join(root, 'config/report.json')), listFiles(path.join(root, 'data/reports')), listFiles(path.join(root, 'data/landscapes'))]);
  const records = [];
  for (const file of [...dailyFiles, ...landscapeFiles].filter(file => file.endsWith('.json'))) records.push({ filePath: path.relative(root, file).replaceAll('\\', '/'), report: await readJson(file) });
  return { taxonomy, config, records };
}
async function atomicWrite(file, content) {
  await mkdir(path.dirname(file), { recursive: true });
  const temporary = `${file}.${process.pid}.${Math.random().toString(16).slice(2)}.tmp`;
  try { await writeFile(temporary, content, 'utf8'); await rename(temporary, file); }
  finally { try { await unlink(temporary); } catch (error) { if (error.code !== 'ENOENT') throw error; } }
}
export async function buildRepository(root, { check = false, now = new Date() } = {}) {
  const { taxonomy, config, records } = await loadRepository(root);
  const errors = validateCollection(records, { taxonomy, config, now });
  if (errors.length) throw new Error(`Validation failed:\n${errors.join('\n')}`);
  const outputs = renderOutputs(records, taxonomy);
  const changed = [];
  const extras = [];
  for (const [relative, content] of outputs) {
    let existing;
    try { existing = await readFile(path.join(root, relative), 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
    if (existing !== content) changed.push(relative);
  }
  const managed = [...await listFiles(path.join(root, 'reports')), ...await listFiles(path.join(root, 'topics')), ...await listFiles(path.join(root, 'landscape'))];
  for (const file of managed) {
    const relative = path.relative(root, file).replaceAll('\\', '/');
    if (outputs.has(relative)) continue;
    const content = file.endsWith('.md') ? await readFile(file, 'utf8') : '';
    const generatedPath = /^reports\/\d{4}\/\d{2}\/\d{4}-\d{2}-\d{2}\.md$/.test(relative) || /^topics\/[^/]+\/[^/]+\/README\.md$/.test(relative) || /^landscape\/\d{4}-\d{2}-\d{2}\.md$/.test(relative);
    const owned = content.startsWith('<!-- Generated by scripts/report.mjs.');
    if (owned || generatedPath) extras.push({ relative, owned });
  }
  if (check) {
    if (changed.length || extras.length) throw new Error(`Generated files are stale. Run npm run build.\n${changed.map(file => `Missing or changed: ${file}`).concat(extras.map(file => `Extra generated path: ${file.relative}`)).join('\n')}`);
  } else {
    const unowned = extras.filter(file => !file.owned);
    if (unowned.length) throw new Error(`Unrecognized files occupy managed generated paths; move or review them before building:\n${unowned.map(file => file.relative).join('\n')}`);
    for (const relative of changed) await atomicWrite(path.join(root, relative), outputs.get(relative));
    for (const extra of extras) await unlink(path.join(root, extra.relative));
  }
  return { reports: records.length, files: outputs.size, changed: changed.length, removed: extras.length };
}
export function createDraft(date, config = {}, now = new Date()) {
  if (!isDate(date)) throw new Error('Draft date must be a valid YYYY-MM-DD date.');
  return { schema_version: 1, date, timezone: config.timezone ?? TIMEZONE, generated_at: now.toISOString(), coverage: scheduledWindow(date, config), search: { status: 'partial', notes: 'Research has not been performed. This draft is not publishable.', sources_checked: [] }, entries: [] };
}
export async function main(args = process.argv.slice(2), root = DEFAULT_ROOT) {
  const [command, ...rest] = args;
  if (command === 'validate' && rest.length === 0) {
    const { taxonomy, config, records } = await loadRepository(root);
    const errors = validateCollection(records, { taxonomy, config });
    if (errors.length) throw new Error(`Validation failed:\n${errors.join('\n')}`);
    console.log(`Validated ${records.length} report(s).`);
  } else if (command === 'build' && (rest.length === 0 || (rest.length === 1 && rest[0] === '--check'))) {
    const result = await buildRepository(root, { check: rest[0] === '--check' });
    console.log(`${rest[0] === '--check' ? 'Checked' : 'Built'} ${result.reports} report(s), ${result.files} generated file(s).`);
  } else if (command === 'new' && rest.length === 1) {
    const config = await readJson(path.join(root, 'config/report.json'));
    const draft = createDraft(rest[0], config);
    const file = path.join(root, 'drafts', `${rest[0]}.json`);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, `${JSON.stringify(draft, null, 2)}\n`, { encoding: 'utf8', flag: 'wx' });
    console.log(`Draft created: ${file}\nNot published. Complete the source review and move the validated report into data/reports/YYYY/MM/.`);
  } else throw new Error('Usage: node scripts/report.mjs validate | build [--check] | new YYYY-MM-DD');
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch(error => { console.error(error.message); process.exitCode = 1; });
}
